# Generated by Django 4.1.5 on 2023-01-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBirthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('isLunar', models.SmallIntegerField(choices=[(1, '公历生日'), (2, '农历生日')], verbose_name='生日')),
            ],
        ),
    ]
